version: '3'
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=foods
    volumes:
      - "./foods_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  web:
      build: 
        context: .
        dockerfile: Dockerfile.dev
      command: npm run serve
      container_name: express_web
      volumes:
      - .:/code
      ports:
      - "3000:3000"
      depends_on:
      - pgdatabase  

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: root12345678
    command: server --address 0.0.0.0:9000 /data --console-address ":9090"        
      